package vsharp.lsp.server;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Optional;
import vsharp.compiler.api.SurfaceVersion;
import java.util.Set;

/// Discovers the Java classpath a source file is compiled against.
///
/// Without this the editor contradicts the compiler. A real V# project declares dependencies
/// to Gradle and passes them to `vsharp --classpath`; the server, compiling the same sources
/// with an empty classpath, reported 330 `VS0246` "type or namespace not found" errors across
/// a real application - every one of them spurious, on files the CLI builds cleanly. An
/// editor that invents errors is worse than one with no diagnostics at all.
///
/// The classpath is read from a `vsharp.classpath` file in the nearest enclosing directory of
/// the source. A file, rather than an editor setting, because the build already knows the
/// answer and a hand-maintained setting drifts from it the first time a dependency changes -
/// the file is generated by the build, so it cannot disagree with what the CLI is given.
/// An explicit `vsharp.server.classpath` setting still wins when one is configured, for
/// projects with no such file.
///
/// Format: one entry per line, or several joined by the platform path separator; blank lines
/// and `#` comments are ignored; a relative entry resolves against the file's own directory.
final class Classpaths {

    private static final System.Logger LOG = System.getLogger(Classpaths.class.getName());

    /// The conventional file name, searched for upwards from each source directory.
    static final String FILE_NAME = "vsharp.classpath";

    /// How far up the tree to look. Deep enough for any real layout
    /// (`root/src/main/vsharp/a/b/C.vs` is six), bounded so a file outside a project does not
    /// walk to the filesystem root on every analysis.
    private static final int MAX_DEPTH = 24;

    private Classpaths() {
        throw new AssertionError("No instances");
    }

    /// The classpath for a set of open documents, in discovery order and without duplicates.
    ///
    /// Several documents usually share one project and therefore one file; a workspace holding
    /// two projects contributes both, which is what lets a single server session serve them.
    static List<Path> forDocuments(Collection<DocumentStore.Document> documents,
            List<Path> configured) {
        Set<Path> entries = new LinkedHashSet<>(configured);
        Set<Path> visited = new LinkedHashSet<>();
        for (DocumentStore.Document document : documents) {
            Optional<Path> descriptor = Uris.toPath(document.uri())
                    .map(Path::toAbsolutePath)
                    .flatMap(path -> locate(path.getParent()));
            if (descriptor.isPresent() && visited.add(descriptor.get())) {
                entries.addAll(read(descriptor.get()));
            }
        }
        return List.copyOf(entries);
    }

    /// The highest surface level any descriptor above these documents requires.
    ///
    /// The build writes `#!surface N` into the descriptor it already generates, so the level
    /// travels by the same route as the classpath and for the same reason: the build knows the
    /// answer and cannot disagree with itself. A descriptor written by a build that predates
    /// the directive records nothing, which reads as "no requirement" and leaves behaviour
    /// exactly as it was.
    ///
    /// @param documents the open documents
    /// @return the highest level required, or empty when no descriptor records one
    static java.util.OptionalInt requiredSurface(
            java.util.Collection<DocumentStore.Document> documents) {
        int required = 0;
        Set<Path> visited = new LinkedHashSet<>();
        for (DocumentStore.Document document : documents) {
            Optional<Path> file = Uris.toPath(document.uri());
            if (file.isEmpty() || file.get().getParent() == null) {
                continue;
            }
            Optional<Path> descriptor = locate(file.get().getParent());
            if (descriptor.isEmpty() || !visited.add(descriptor.get())) {
                continue;
            }
            List<String> lines;
            try {
                lines = Files.readAllLines(descriptor.get(), StandardCharsets.UTF_8);
            } catch (IOException | UncheckedIOException e) {
                continue;
            }
            for (String line : lines) {
                java.util.OptionalInt level = SurfaceVersion.parse(line);
                if (level.isPresent()) {
                    required = Math.max(required, level.getAsInt());
                }
            }
        }
        return required == 0 ? java.util.OptionalInt.empty() : java.util.OptionalInt.of(required);
    }

    /// The nearest `vsharp.classpath` at or above `directory`.
    private static Optional<Path> locate(Path directory) {
        Path current = directory;
        for (int depth = 0; current != null && depth < MAX_DEPTH; depth++) {
            Path candidate = current.resolve(FILE_NAME);
            if (Files.isRegularFile(candidate)) {
                return Optional.of(candidate);
            }
            current = current.getParent();
        }
        return Optional.empty();
    }

    /// Parses one descriptor. A malformed or unreadable file yields no entries and a warning:
    /// refusing to analyse at all would leave the user with a silent editor and no reason.
    private static List<Path> read(Path descriptor) {
        List<String> lines;
        try {
            lines = Files.readAllLines(descriptor, StandardCharsets.UTF_8);
        } catch (IOException | UncheckedIOException e) {
            LOG.log(System.Logger.Level.WARNING, "Could not read " + descriptor, e);
            return List.of();
        }
        Path base = descriptor.getParent();
        List<Path> entries = new ArrayList<>();
        for (String line : lines) {
            String text = line.strip();
            if (text.isEmpty() || text.startsWith("#")) {
                continue;
            }
            for (String piece : text.split(java.util.regex.Pattern.quote(java.io.File.pathSeparator))) {
                String entry = piece.strip();
                if (entry.isEmpty()) {
                    continue;
                }
                try {
                    Path resolved = base.resolve(entry).normalize();
                    // A stale descriptor naming a jar that no longer exists would make the
                    // compiler's own resolution fail; skipping keeps the rest usable.
                    if (Files.exists(resolved)) {
                        entries.add(resolved);
                    } else {
                        LOG.log(System.Logger.Level.DEBUG, "Classpath entry is absent: {0}",
                                resolved);
                    }
                } catch (java.nio.file.InvalidPathException e) {
                    LOG.log(System.Logger.Level.WARNING, "Bad classpath entry '" + entry
                            + "' in " + descriptor, e);
                }
            }
        }
        return entries;
    }
}
