/// V# runtime support module.
///
/// Contains the small set of helpers that compiler-generated bytecode links against:
/// C#-faithful value formatting, `Index`/`Range` offset computation, slicing, and
/// value tuples. Everything here is JDK-only and side-effect free apart from the
/// explicit console surface in [vsharp.runtime.stdlib].
module vsharp.runtime {
    exports vsharp.runtime;
    exports vsharp.runtime.stdlib;
}
